### PR TITLE
Fix Clock

### LINKED ISSUE #496: Clock causes enemies with multiple directional sprites to teleport all over the place

### PR DESCRIPTION
**Pull request by mdcurie11**
Fix clock making multi sprite enemies freak out. I also added a cheat code (C + G) to spawn a clock right in front of link, as an additional cheat code, but also to make testing this easier.

Closes #496

### CODE REVIEW

**Review by turtenguin — CHANGES_REQUESTED** [review]
Works for Goriya but not Dodongo. You can go ahead and merge if we don't plan to fix the dodongo issues.

**Comment by mdcurie11** [comment]
> Works for Goriya but not Dodongo. You can go ahead and merge if we don't plan to fix the dodongo issues.

Sorry I overlooked that. I'll fix that rq.

**Comment by mdcurie11** [comment]
@turtenguin Should be corrected now, thanks for the catch and srry for overlooking it agian!

**Comment by EthanGlenwright775** [comment]
Looks great thanks for fixing!

**Pull request merged**
